############################################
# APIリクエストサンプル集
#
############################################

@url = http://localhost:4001
#@url = https://

###ログイン(ユーザー認証)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "fugafuga@example.com", 
    "password": "fugafuga"
  }

###ログイン(アカウント＋ユーザー認証)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "account": "hogehoge account",
    "email": "hogehoge@example.com", 
    "password": "hogehoge"
  }

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJNYXRlcmlhIiwiZW1haWwiOiJmdWdhZnVnYUBleGFtcGxlLmNvbSIsImV4cCI6MTU1MzEwMDE5NywiaWF0IjoxNTUzMDk5NTk3LCJpc3MiOiJNYXRlcmlhIiwianRpIjoiYTBmOGQ2NjctZTljMS00ZTA4LTk0NjktNTgwNDE3NzQ1YWU4IiwibmJmIjoxNTUzMDk5NTk2LCJzdWIiOiJ7XCJ1c2VyX2lkXCI6Mn0iLCJ0eXAiOiJhY2Nlc3MifQ.fK-YItR0zicGa6gF9CQUyr7_brCnRDDsG87oRapI3pI


### ユーザー汎用検索
POST {{url}}/api/search-users HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

 {
    "and": [{"role": "admin"}],
    "or": [{"status": 8}, {"status": 1}]
  }

### ユーザー汎用検索
GET {{url}}/api/ops/users/1 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

### 論理削除
PUT {{url}}/api/delete-users/1 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "lock_version": 2
}

###
