############################################
# APIリクエストサンプル集
#
############################################

@url = http://localhost:4001
#@url = https://

### ユーザー登録
POST {{url}}/api/ops/users HTTP/1.1
Content-Type: application/json

 {
    "name": "hogehoge太郎",
    "email": "admin@example.com", 
    "password": "password",
    "role": "admin"
  }

### メール認証

POST {{url}}/api/verify_user HTTP/1.1
Content-Type: application/json

 {
    "verify_key": "hogehoge",
    "email": "admin@example.com", 
    "password": "password"
  }

###ログイン
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "hogehoge@example.com", 
    "password": "hogehoge"
  }


###ログイン
POST {{url}}/api/sign-in-with-refresh HTTP/1.1
Content-Type: application/json

{
    "email": "hogehoge@example.com", 
    "password": "hogehoge"
  }

###ログイン
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "fugafuga@example.com", 
    "password": "fugafuga"
  }

###ログイン(メールアドレス相違)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "notexists@example.com", 
    "password": "hogehoge"
  }

###ログイン(パスワード相違)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "hogehoge@example.com", 
    "password": "fugafuga"
  }

@token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJTZXJ2aWNleCIsImVtYWlsIjoiZnVnYWZ1Z2FAZXhhbXBsZS5jb20iLCJleHAiOjE1NDA1NDYwOTEsImlhdCI6MTU0MDU0NTQ5MSwiaXNzIjoiU2VydmljZXgiLCJqdGkiOiI4NGEzNDZiNi05MWZiLTRmNmQtOWRmNS0wMjQxYTNiMTUzNTMiLCJuYmYiOjE1NDA1NDU0OTAsInN1YiI6IjIiLCJ0eXAiOiJhY2Nlc3MifQ.D1flaKkd-CkP8uAnsWy45k-xvovw23jmEGEGpPPDvtVfQZy5KWNNBGKevEZ0zpoZUMCEuRr58kRNs6QqoUuzPg

###認証チェック

GET {{url}}/api/auth-check HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###トークンリフレッシュ

POST {{url}}/api/refresh HTTP/1.1
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJTZXJ2aWNleCIsImVtYWlsIjoiZnVnYWZ1Z2FAZXhhbXBsZS5jb20iLCJleHAiOjE1NDA2MzE4OTEsImlhdCI6MTU0MDU0NTQ5MSwiaXNzIjoiU2VydmljZXgiLCJqdGkiOiIyNjJjZWU0Ny03ODBiLTQxMjctYjJkNi1lYTYyMmM4MWE4NjkiLCJuYmYiOjE1NDA1NDU0OTAsInN1YiI6IjIiLCJ0eXAiOiJyZWZyZXNoIn0.XR98gJ2HyESLAUFWkoOp38fTxJ9Qy4Y8tWV8aQzBkxohRzxEtfmklNGyLGmh-rHA2ELdUm9JrYa8yu7DL-qQoA"
}


###ユーザー情報照会(一般ユーザー用)
GET {{url}}/api/user HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###ユーザー一覧照会(オペレーター用)
GET {{url}}/api/ops/users HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###ユーザー情報照会(オペレーター用)
GET {{url}}/api/ops/users/2 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###権限情報一覧照会
GET {{url}}/api/ops/grants HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###権限情報照会
GET {{url}}/api/ops/grants/4 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###ロール指定の権限照会
POST {{url}}/api/grant HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "role": "admin"
}


###ログアウト
POST {{url}}/api/sign-out HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
