############################################
# APIリクエストサンプル集
#
############################################

@url = http://localhost:4000
#@url = https://

###ユーザー登録
POST {{url}}/api/users HTTP/1.1
Content-Type: application/json

 {
    "name": "hogehoge太郎",
    "email": "admin@example.com", 
    "password": "password",
    "role": "admin"
  }


###ログイン
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "hogehoge@example.com", 
    "password": "hogehoge"
  }

###ログイン
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "fugafuga@example.com", 
    "password": "fugafuga"
  }

###ログイン(メールアドレス相違)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "notexists@example.com", 
    "password": "hogehoge"
  }

###ログイン(パスワード相違)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "hogehoge@example.com", 
    "password": "fugafuga"
  }

@token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJTZXJ2aWNleCIsImV4cCI6MTUzMTg4OTM0MSwiaWF0IjoxNTI5NDcwMTQxLCJpc3MiOiJTZXJ2aWNleCIsImp0aSI6IjMxMjg0ZDE1LTk3N2YtNGZlMi1hYmI3LWU3MjI4MGRhNThlNyIsIm5iZiI6MTUyOTQ3MDE0MCwic3ViIjoiMiIsInR5cCI6ImFjY2VzcyJ9.rgSYvWLdeyHD3fSV0busPzk6aNbKYZKyPau9oGe2DZHuGLb7i1LNbE-DRqiJtX6Wze9s-ptg4OA0j6BOu3GTkg

###ユーザー情報照会(一般ユーザー用)
GET {{url}}/api/user HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###ユーザー一覧照会(オペレーター用)
GET {{url}}/api/ops/users HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###ユーザー情報照会(オペレーター用)
GET {{url}}/api/ops/users/2 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###権限情報一覧照会
GET {{url}}/api/ops/grants HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###権限情報照会
GET {{url}}/api/ops/grants/4 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###ロール指定の権限照会
POST {{url}}/api/grant HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "role": "admin"
}


###ログアウト
POST {{url}}/api/sign-out HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
