############################################
# APIリクエストサンプル集
#
############################################

@url = http://localhost:4000
#@url = https://

###ユーザー登録
POST {{url}}/api/users HTTP/1.1
Content-Type: application/json

{
"user": {
    "name": "hogehoge太郎",
    "email": "admin@example.com", 
    "password": "password",
    "role": "admin"
  }
}

###ログイン
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "hogehoge@example.com", 
    "password": "hogehoge"
  }

###ログイン
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "fugafuga@example.com", 
    "password": "fugafuga"
  }

###ログイン(メールアドレス相違)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "notexists@example.com", 
    "password": "hogehoge"
  }

###ログイン(パスワード相違)
POST {{url}}/api/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "hogehoge@example.com", 
    "password": "fugafuga"
  }

@token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhcHBfZXgiLCJleHAiOjE1MzE3OTY3NzYsImlhdCI6MTUyOTM3NzU3NiwiaXNzIjoiYXBwX2V4IiwianRpIjoiNjY3NWVjYjYtNmViYS00YjI0LTk0MGYtMjdmMWU0MzQ1OWM4IiwibmJmIjoxNTI5Mzc3NTc1LCJzdWIiOiIzIiwidHlwIjoiYWNjZXNzIn0.ZAUuJbxbHEiAe1uQBTC2vhlH58NqZdf5Q5RQfd4R0oj8z-VHrf_uv9saZJS4aQ0d4bzrLrADl820LQzt3G1h8w

###ユーザー情報照会(一般ユーザー用)
GET {{url}}/api/user HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###ユーザー一覧照会(オペレーター用)
GET {{url}}/api/ops/users HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###ユーザー情報照会(オペレーター用)
GET {{url}}/api/ops/users/4 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###権限情報照会
GET {{url}}/api/ops/grants HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###ログアウト
POST {{url}}/api/sign-out HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
