############################################
# APIリクエストサンプル集
#
############################################

@url = http://localhost:4001
#@url = https://

###汎用システムヘルスチェック
# result image
# {"message":"health_check_ok"}
GET {{url}}/api/health-check HTTP/1.1
Content-Type: application/json




